window.QUIZ_DATA = window.QUIZ_DATA || {};
window.QUIZ_DATA["day44"] = {
  title: "DataStage Architecture",
  topics: ["Designer Client", "Director Client", "Administrator", "Repository", "Engine Tier"],
  questions: [
    {
      id: 1,
      type: "single",
      difficulty: 1,
      question: "What is the primary purpose of the IBM DataStage Designer Client?",
      options: ["To design, develop, and compile ETL jobs", "To schedule and monitor running jobs in production", "To administer user accounts and project settings", "To manage repository backups and disaster recovery"],
      correct: [0],
      concept: "The Designer Client is the development environment where ETL developers create, modify, and compile DataStage jobs. It provides a graphical canvas for designing data flows using stages, links, and transformations."
    },
    {
      id: 2,
      type: "single",
      difficulty: 1,
      question: "Which DataStage client is used to execute and monitor jobs at runtime?",
      options: ["Designer Client", "Director Client", "Administrator Client", "Manager Client"],
      correct: [1],
      concept: "The Director Client is the operational interface used to run, schedule, and monitor DataStage jobs. It provides views for job status, logs, and scheduling, making it the go-to tool for production operations."
    },
    {
      id: 3,
      type: "single",
      difficulty: 1,
      question: "What does the Designer canvas provide in DataStage?",
      options: ["A graphical workspace for building data flow logic visually", "A command-line interface for scripting job definitions", "A dashboard for viewing real-time job execution metrics", "A configuration panel for setting engine tier parameters"],
      correct: [0],
      concept: "The Designer canvas is a drag-and-drop graphical workspace where developers place stages (sources, targets, transformers) and connect them with links to define the data flow logic of a job."
    },
    {
      id: 4,
      type: "single",
      difficulty: 1,
      question: "Which component of IBM Information Server hosts the DataStage engine?",
      options: ["Services Tier", "Engine Tier", "Client Tier", "Repository Tier"],
      correct: [1],
      concept: "The Engine Tier hosts the DataStage processing engines that execute jobs. It is the compute layer of the Information Server architecture, separate from the Services Tier (which hosts web services) and the Client Tier (which hosts desktop clients)."
    },
    {
      id: 5,
      type: "single",
      difficulty: 1,
      question: "What is the palette in the DataStage Designer Client?",
      options: ["A panel listing available stages that can be placed on the canvas", "A color-coding scheme for differentiating job types", "A toolbar for formatting the appearance of job diagrams", "A sidebar showing the project hierarchy and folders"],
      correct: [0],
      concept: "The palette in the Designer Client is a categorized panel that lists all available stages (e.g., Sequential File, Transformer, Join, Lookup). Developers drag stages from the palette onto the canvas to build jobs."
    },
    {
      id: 6,
      type: "single",
      difficulty: 1,
      question: "Which IBM Information Server architecture tier hosts the metadata repository database?",
      options: ["Client Tier", "Engine Tier", "Services Tier", "Compute Tier"],
      correct: [2],
      concept: "The Services Tier (also called the middle tier) hosts the metadata repository database along with web-based services, security components, and the common metadata infrastructure used across Information Server suite products."
    },
    {
      id: 7,
      type: "single",
      difficulty: 1,
      question: "What type of database is typically used to store the DataStage repository?",
      options: ["A relational database such as DB2 or Oracle", "A NoSQL document store like MongoDB", "A flat file system on the engine tier", "An in-memory cache database like Redis"],
      correct: [0],
      concept: "The DataStage repository is stored in a relational database, commonly IBM DB2, but Oracle and other supported RDBMS can also be used. This database holds all metadata, job definitions, table definitions, and project information."
    },
    {
      id: 8,
      type: "single",
      difficulty: 1,
      question: "In the DataStage Director Client, what does the job status view display?",
      options: ["The current state of jobs such as running, finished, or aborted", "The list of stages inside a job design", "The SQL queries generated by each stage", "The column definitions of source and target tables"],
      correct: [0],
      concept: "The Director Client\'s status view shows the current state of each job instance, including statuses like Running, Finished, Finished with warnings, Aborted, and others. This is the primary view for monitoring job execution."
    },
    {
      id: 9,
      type: "single",
      difficulty: 1,
      question: "What is the Administrator Client primarily used for in DataStage?",
      options: ["Designing and coding ETL transformation logic", "Managing projects, users, and system configuration", "Writing SQL queries for data extraction", "Scheduling and triggering batch job execution"],
      correct: [1],
      concept: "The Administrator Client (also accessible via the web console) is used for project-level administration including creating/deleting projects, managing user permissions, configuring environment variables, and setting system-wide configuration options."
    },
    {
      id: 10,
      type: "single",
      difficulty: 1,
      question: "What is a DataStage project in terms of the repository?",
      options: ["A logical container organizing related jobs, table definitions, and shared objects", "A physical server instance running the DataStage engine", "A user account with specific permissions and roles", "A backup copy of the repository database for recovery"],
      correct: [0],
      concept: "A DataStage project is a logical grouping within the repository that organizes related assets such as jobs, table definitions, shared containers, data connections, and other metadata objects. Multiple projects can exist within a single DataStage installation."
    },
    {
      id: 11,
      type: "single",
      difficulty: 1,
      question: "Which file type defines the parallel engine\'s hardware configuration in DataStage?",
      options: ["The APT configuration file (.apt)", "The DSParams configuration file", "The job sequence XML file (.xml)", "The DSEngine environment script (.sh)"],
      correct: [0],
      concept: "The APT configuration file (.apt) defines the hardware topology for the parallel engine, including processing nodes, node pools, resource disks, and scratch disk locations. It controls how parallelism is distributed across available hardware."
    },
    {
      id: 12,
      type: "single",
      difficulty: 1,
      question: "How are jobs organized within a DataStage project in the repository?",
      options: ["In a hierarchical folder structure with categories and subcategories", "In a flat list sorted by creation date only", "In a relational schema with normalized tables", "In version-controlled branches like a Git repository"],
      correct: [0],
      concept: "DataStage projects use a folder-based hierarchy where jobs and other objects are organized into categories (folders) and subcategories. This structure helps developers manage large numbers of jobs by grouping them logically."
    },
    {
      id: 13,
      type: "single",
      difficulty: 1,
      question: "What is the purpose of environment variables in DataStage?",
      options: ["To parameterize job behavior and engine configuration at runtime", "To define the visual layout of stages on the Designer canvas", "To set color themes for the Director Client interface", "To encrypt sensitive data stored in the repository database"],
      correct: [0],
      concept: "Environment variables in DataStage allow administrators and developers to parameterize configurations such as file paths, database connections, buffer sizes, and parallel processing settings. They can be set at the project, job, or system level."
    },
    {
      id: 14,
      type: "single",
      difficulty: 1,
      question: "What does SMP stand for in the context of DataStage engine architecture?",
      options: ["Symmetric Multiprocessing", "Sequential Message Processing", "Shared Memory Partitioning", "Staged Metadata Pipeline"],
      correct: [0],
      concept: "SMP stands for Symmetric Multiprocessing, a hardware architecture where multiple processors share the same memory and I/O resources. DataStage can run on SMP systems where the parallel engine uses multiple CPUs within a single server."
    },
    {
      id: 15,
      type: "single",
      difficulty: 1,
      question: "What does MPP stand for in DataStage parallel processing?",
      options: ["Multi-Pipeline Processing", "Massively Parallel Processing", "Managed Process Partitioning", "Multiple Platform Provisioning"],
      correct: [1],
      concept: "MPP stands for Massively Parallel Processing, where multiple independent processing nodes each have their own memory and storage. DataStage\'s parallel engine can leverage MPP architectures to distribute workloads across many nodes for large-scale data processing."
    },
    {
      id: 16,
      type: "single",
      difficulty: 1,
      question: "Which view in the Director Client allows you to see the detailed execution log of a completed job?",
      options: ["The Schedule view", "The Log view", "The Design view", "The Repository view"],
      correct: [1],
      concept: "The Log view in the Director Client displays detailed runtime messages generated during job execution, including informational messages, warnings, and error details. It is essential for troubleshooting job failures."
    },
    {
      id: 17,
      type: "single",
      difficulty: 1,
      question: "What is the role of node pools in a DataStage APT configuration file?",
      options: ["They group processing nodes that share similar resource characteristics", "They define the maximum number of concurrent users per project", "They specify the database connection parameters for the repository", "They configure the authentication mechanism for client access"],
      correct: [0],
      concept: "Node pools in the APT configuration file group processing nodes with similar characteristics (e.g., same CPU type, memory, disk speed). The parallel engine uses node pools to allocate resources effectively and distribute processing across appropriate nodes."
    },
    {
      id: 18,
      type: "single",
      difficulty: 1,
      question: "What happens when you compile a job in the DataStage Designer Client?",
      options: ["The job design is validated and converted into an executable runtime representation", "The job is immediately executed on the engine tier", "The job is exported as a portable XML package for migration", "The job is published to the Director Client for scheduling"],
      correct: [0],
      concept: "Compiling a job in the Designer Client validates the job design for errors and generates the executable runtime code (OSH script for parallel jobs). A job must be compiled successfully before it can be run in the Director."
    },
    {
      id: 19,
      type: "single",
      difficulty: 1,
      question: "Which DataStage component is responsible for processing data in parallel using pipeline and partition parallelism?",
      options: ["The Designer Client rendering engine", "The parallel engine on the Engine Tier", "The repository database query optimizer", "The Director Client scheduling module"],
      correct: [1],
      concept: "The parallel engine on the Engine Tier is the core processing component that executes parallel jobs. It implements both pipeline parallelism (overlapping stage execution) and partition parallelism (splitting data across multiple processing instances)."
    },
    {
      id: 20,
      type: "single",
      difficulty: 1,
      question: "How do you import a DataStage job from one environment to another?",
      options: ["Export the job as a .dsx file and import it into the target project", "Copy the repository database tables directly between servers", "Re-create the job manually using screenshots from the source", "Use the Director Client to transfer running job instances"],
      correct: [0],
      concept: "DataStage jobs are exported as .dsx (DataStage Exchange) files, which are XML-based files containing the complete job definition, metadata, and dependencies. These files can then be imported into another project or environment."
    },
    {
      id: 21,
      type: "single",
      difficulty: 1,
      question: "What is the primary function of the IBM Information Server Services Tier?",
      options: ["To host web services, security, metadata management, and shared infrastructure", "To provide the graphical user interface for job development", "To execute ETL transformation logic at maximum throughput", "To store raw data files for staging area processing"],
      correct: [0],
      concept: "The Services Tier is the middle layer of the Information Server architecture. It hosts common services including the metadata repository, security and authentication, logging, web console, and APIs that are shared across all Information Server modules."
    },
    {
      id: 22,
      type: "single",
      difficulty: 1,
      question: "In DataStage, what is a table definition?",
      options: ["A metadata object describing the structure (columns, types) of a data source or target", "A physical database table created automatically by the engine during job execution", "A runtime log table that records row counts for each processed batch", "A configuration table defining the APT file parameters for the parallel engine"],
      correct: [0],
      concept: "A table definition is a metadata object in the repository that describes the schema of a data source or target, including column names, data types, lengths, and nullability. Table definitions are reused across jobs to ensure consistent metadata."
    },
    {
      id: 23,
      type: "single",
      difficulty: 1,
      question: "Which IBM Information Server component provides a web-based administration console?",
      options: ["DataStage Designer", "Information Server Web Console", "DataStage Director", "Quality Stage Client"],
      correct: [1],
      concept: "The Information Server Web Console is a browser-based administration interface that provides centralized management capabilities including user administration, project management, logging configuration, and system monitoring across the Information Server suite."
    },
    {
      id: 24,
      type: "single",
      difficulty: 1,
      question: "What is the job run history in the Director Client?",
      options: ["A record of all previous executions of a job including start time, end time, and status", "A changelog tracking modifications made to the job design over time", "A backup log of exported .dsx files for the project", "A list of user login attempts to the Director Client interface"],
      correct: [0],
      concept: "Job run history in the Director Client maintains a historical record of all job executions, including timestamps, duration, final status (finished, aborted, etc.), and associated log entries. This is valuable for auditing, trend analysis, and troubleshooting."
    },
    {
      id: 25,
      type: "single",
      difficulty: 1,
      question: "What are the three main client applications in the traditional DataStage architecture?",
      options: ["Designer, Director, and Administrator", "Builder, Runner, and Controller", "Developer, Executor, and Manager", "Modeler, Scheduler, and Configurator"],
      correct: [0],
      concept: "The three main DataStage client applications are: Designer (for job development), Director (for job execution and monitoring), and Administrator (for project and system configuration). Together they cover the full lifecycle of DataStage job management."
    },
    {
      id: 26,
      type: "single",
      difficulty: 1,
      question: "Which DataStage job type runs stages sequentially on a single processing node?",
      options: ["Parallel job", "Server job", "Mainframe job", "Container job"],
      correct: [1],
      concept: "Server jobs (also called sequential jobs) execute stages one at a time on a single processing node without data partitioning. They use the server engine and are limited compared to parallel jobs in terms of scalability and performance."
    },
    {
      id: 27,
      type: "single",
      difficulty: 1,
      question: "What is the purpose of resource management in the DataStage engine tier?",
      options: ["To allocate CPU, memory, and disk resources efficiently across parallel processing nodes", "To manage the licensing and subscription costs of the DataStage installation", "To schedule user access times for the Designer Client interface", "To track the number of rows processed for billing purposes"],
      correct: [0],
      concept: "Resource management in the engine tier ensures efficient allocation and utilization of computing resources (CPU cores, memory, disk I/O) across processing nodes. The APT configuration file and resource settings control how the parallel engine distributes workloads."
    },
    {
      id: 28,
      type: "single",
      difficulty: 1,
      question: "How does the Designer Client connect to the DataStage server?",
      options: ["Through a direct TCP/IP connection to the engine tier using the DataStage RPC protocol", "Through a REST API served by the web console", "Through ODBC connections to the repository database", "Through SSH tunneling to the operating system command line"],
      correct: [0],
      concept: "The Designer Client connects to the DataStage server via a TCP/IP connection using a proprietary RPC (Remote Procedure Call) protocol. The connection is established by specifying the server hostname, project name, and user credentials."
    },
    {
      id: 29,
      type: "single",
      difficulty: 1,
      question: "What is the function of the schedule view in the Director Client?",
      options: ["It displays the design-time layout of stages within a job", "It shows scheduled job runs including frequency, start time, and trigger conditions", "It lists the columns and data types of each stage in a job", "It presents a Gantt chart of all projects in the repository"],
      correct: [1],
      concept: "The schedule view in the Director Client displays all scheduled job executions, including their frequency (daily, weekly, etc.), next run time, and any trigger conditions or dependencies. It is used to manage and monitor job scheduling."
    },
    {
      id: 30,
      type: "single",
      difficulty: 1,
      question: "What type of objects can be stored in the DataStage repository?",
      options: ["Jobs, table definitions, shared containers, data connections, and routines", "Only compiled binary executables of parallel jobs", "Only raw data files and staging area datasets", "Only user credentials and access control lists"],
      correct: [0],
      concept: "The DataStage repository stores a wide variety of metadata objects including job designs, table definitions, shared containers, data connections, parameter sets, custom routines, transforms, and stage types. It is the central metadata store for all development assets."
    },
    {
      id: 31,
      type: "single",
      difficulty: 1,
      question: "Which DataStage architecture tier is installed on the developer\'s workstation?",
      options: ["Engine Tier", "Services Tier", "Client Tier", "Repository Tier"],
      correct: [2],
      concept: "The Client Tier consists of the desktop applications (Designer, Director, Administrator) installed on the developer\'s or operator\'s workstation. These thick clients connect remotely to the server-side Engine and Services tiers."
    },
    {
      id: 32,
      type: "single",
      difficulty: 1,
      question: "What is the purpose of the DSParams file in DataStage?",
      options: ["It stores project-level environment variable settings and configuration parameters", "It contains the compiled binary code of all parallel jobs in the project", "It defines the network topology for multi-server deployments", "It records the audit trail of all user actions in the repository"],
      correct: [0],
      concept: "The DSParams file is a project-level configuration file that stores environment variable settings, default job parameter values, and other configuration parameters. Changes made through the Administrator Client are often persisted in this file."
    },
    {
      id: 33,
      type: "single",
      difficulty: 1,
      question: "In DataStage, what does exporting a job as a .dsx file include?",
      options: ["The job design, dependent table definitions, shared containers, and metadata", "Only the compiled executable code without any metadata", "The actual data processed by the job during its last execution", "The Director Client schedule and run history for the job"],
      correct: [0],
      concept: "A .dsx export includes the complete job design along with all dependent objects such as table definitions, shared containers, parameter sets, and routines. This ensures that the job can be fully reconstructed when imported into another environment."
    },
    {
      id: 34,
      type: "single",
      difficulty: 1,
      question: "What is a processing node in the context of the DataStage parallel engine?",
      options: ["A logical processing unit defined in the APT configuration file that executes a portion of a parallel job", "A physical server dedicated exclusively to running the Director Client", "A database instance hosting a partition of the repository metadata", "A network switch connecting multiple DataStage client workstations"],
      correct: [0],
      concept: "A processing node is a logical unit defined in the APT configuration file. It represents a processing instance that the parallel engine uses to execute a portion of a job. Multiple logical nodes can map to a single physical server in SMP configurations."
    },
    {
      id: 35,
      type: "single",
      difficulty: 1,
      question: "Which DataStage feature allows you to view the data flowing between stages during job development?",
      options: ["The data preview or row peek capability in the Designer Client", "The schedule view in the Director Client", "The environment variable editor in the Administrator Client", "The repository export utility in the command line"],
      correct: [0],
      concept: "The Designer Client provides a data preview (or row peek) feature that allows developers to view sample data flowing between stages during development and testing. This helps validate transformation logic before deploying jobs to production."
    },
    {
      id: 36,
      type: "single",
      difficulty: 2,
      question: "When a DataStage parallel job is compiled, what intermediate representation is generated?",
      options: ["An OSH (Orchestrate Shell) script describing the parallel execution plan", "A standard SQL script for execution on the target database", "A Java bytecode JAR file for the JVM-based engine", "A Python pickle file containing serialized stage objects"],
      correct: [0],
      concept: "When a parallel job is compiled, the Designer generates an OSH (Orchestrate Shell) script. This script describes the data flow graph, operators, partitioning, and execution plan that the parallel engine interprets at runtime to execute the job."
    },
    {
      id: 37,
      type: "single",
      difficulty: 2,
      question: "In the APT configuration file, what does the \"resource disk\" parameter specify?",
      options: ["The disk location used for temporary storage during parallel processing operations", "The disk where the repository database files are permanently stored", "The disk location for archiving completed job log files", "The disk path for storing exported .dsx backup files"],
      correct: [0],
      concept: "The resource disk in the APT configuration file specifies the disk location used for temporary data storage during parallel processing, such as sort operations, hash joins, and intermediate data spills. Adequate resource disk space is critical for performance."
    },
    {
      id: 38,
      type: "single",
      difficulty: 2,
      question: "What happens when you attempt to run a job in the Director Client that has not been compiled?",
      options: ["The Director automatically compiles and then runs the job", "The Director displays an error indicating the job must be compiled first", "The Director runs the job using the previous compiled version", "The Director prompts the user to switch to the Designer Client"],
      correct: [1],
      concept: "A DataStage job must be compiled successfully in the Designer Client before it can be executed in the Director. Attempting to run an uncompiled or failed-to-compile job results in an error because no executable runtime representation exists."
    },
    {
      id: 39,
      type: "single",
      difficulty: 2,
      question: "How does the DataStage parallel engine achieve pipeline parallelism?",
      options: ["By executing multiple stages simultaneously, with data flowing between them in a streaming fashion", "By running the same stage multiple times with different parameter values", "By splitting the job design into separate .dsx files processed independently", "By duplicating the repository database across multiple servers"],
      correct: [0],
      concept: "Pipeline parallelism means that multiple stages in a job execute concurrently, with data streaming from one stage to the next without waiting for a stage to fully complete. This overlapping execution significantly reduces total job elapsed time."
    },
    {
      id: 40,
      type: "single",
      difficulty: 2,
      question: "What is the difference between the scratch disk and the resource disk in the APT configuration?",
      options: ["Scratch disk is for buffering inter-process data; resource disk is for large sort and hash temporary files", "Scratch disk is for permanent storage; resource disk is for temporary log files", "They are identical and the terms are interchangeable in all contexts", "Scratch disk is used by the Designer; resource disk is used by the Director"],
      correct: [0],
      concept: "In the APT configuration, the scratch disk is used for buffering data passed between operators (inter-process communication), while the resource disk is used for large temporary data generated by sort, hash join, and other resource-intensive operations."
    },
    {
      id: 41,
      type: "single",
      difficulty: 2,
      question: "In the Administrator Client, which setting controls the maximum number of job instances that can run concurrently in a project?",
      options: ["The job run limit or maximum concurrent jobs setting", "The repository database connection pool size", "The APT configuration file node count", "The Director Client refresh interval setting"],
      correct: [0],
      concept: "The Administrator Client allows setting a maximum number of concurrent job instances per project. This job run limit prevents resource exhaustion on the engine tier by controlling how many jobs can execute simultaneously."
    },
    {
      id: 42,
      type: "single",
      difficulty: 2,
      question: "What does the DataStage Administrator Client allow you to configure regarding user access?",
      options: ["User roles, project membership, and access privileges for DataStage operations", "The IP address whitelist for the parallel engine network", "The encryption algorithm used for data at rest in staging files", "The physical memory allocation for each user\'s Designer Client session"],
      correct: [0],
      concept: "The Administrator Client manages user security including assigning roles (Developer, Operator, etc.), granting project membership, and configuring access privileges that control which operations each user can perform within DataStage."
    },
    {
      id: 43,
      type: "single",
      difficulty: 2,
      question: "When importing a .dsx file into a DataStage project, what happens if an object with the same name already exists?",
      options: ["The system prompts the user to choose whether to replace, rename, or skip the conflicting object", "The import automatically overwrites the existing object without warning", "The import fails entirely and no objects are imported", "The existing object is archived and the new version is imported as a copy"],
      correct: [0],
      concept: "During .dsx import, DataStage detects naming conflicts and presents options to the user: replace the existing object, rename the incoming object, or skip the conflicting object. This conflict resolution ensures controlled management of metadata assets."
    },
    {
      id: 44,
      type: "single",
      difficulty: 2,
      question: "What is the relationship between the Information Server engine tier and the DataStage parallel engine?",
      options: ["The parallel engine is a key component hosted within the engine tier that executes parallel jobs", "The parallel engine is a separate product that runs independently of the engine tier", "The engine tier only supports server (sequential) jobs, not parallel jobs", "The parallel engine replaces the engine tier entirely in modern installations"],
      correct: [0],
      concept: "The DataStage parallel engine is a core component within the Information Server engine tier. The engine tier provides the runtime environment where the parallel engine processes jobs using data partitioning and pipeline parallelism."
    },
    {
      id: 45,
      type: "single",
      difficulty: 2,
      question: "How does the Director Client differentiate between a job that finished successfully and one that finished with warnings?",
      options: ["Different status icons and labels: \"Finished\" for success and \"Finished (with warnings)\" for warnings", "By the color of the log view background: green for success, yellow for warnings", "There is no differentiation; both show as \"Finished\" in the status view", "By the number of output rows displayed in the job metrics panel"],
      correct: [0],
      concept: "The Director Client uses distinct status labels and icons to differentiate job outcomes. A job that completes without issues shows as \"Finished\" while one that completes but generated warning messages shows as \"Finished (with warnings).\""
    },
    {
      id: 46,
      type: "single",
      difficulty: 2,
      question: "What is the purpose of the $APT_CONFIG_FILE environment variable in DataStage?",
      options: ["It specifies the path to the APT configuration file used by the parallel engine at runtime", "It defines the default export directory for .dsx files", "It sets the logging level for the Director Client interface", "It configures the timeout value for Designer Client connections"],
      correct: [0],
      concept: "The $APT_CONFIG_FILE environment variable tells the parallel engine which APT configuration file to use when executing a job. Different jobs can use different configuration files to optimize resource usage for varying workload sizes."
    },
    {
      id: 47,
      type: "single",
      difficulty: 2,
      question: "Which of the following best describes how a parallel job distributes data across processing nodes?",
      options: ["Data is partitioned into segments and each segment is processed by a different node instance", "Data is replicated to every node so each processes the complete dataset independently", "Data remains on a single node while processing instructions are distributed to other nodes", "Data is compressed and stored in shared memory accessible by all nodes simultaneously"],
      correct: [0],
      concept: "Parallel jobs use data partitioning to split data into segments (partitions) that are distributed across processing nodes. Each node processes its partition independently, achieving partition parallelism. This divide-and-conquer approach enables high-throughput data processing."
    },
    {
      id: 48,
      type: "single",
      difficulty: 2,
      question: "In DataStage, what is the function of the repository category tree?",
      options: ["To organize jobs and other objects into a hierarchical folder structure for easy navigation", "To categorize error messages by severity level in the Director log view", "To classify data types into atomic and composite categories for the Transformer stage", "To rank processing nodes by performance tier in the APT configuration"],
      correct: [0],
      concept: "The repository category tree provides a hierarchical folder structure within a project to organize jobs, shared containers, table definitions, and other objects. Developers create categories and subcategories to maintain an orderly project structure."
    },
    {
      id: 49,
      type: "single",
      difficulty: 2,
      question: "What role does the DataStage engine play when a server (sequential) job is executed?",
      options: ["The server engine processes stages one at a time using a single process on one node", "The server engine distributes data across all available nodes for parallel execution", "The server engine only validates the job design without actually processing data", "The server engine compiles the job into an OSH script before executing it"],
      correct: [0],
      concept: "When a server job runs, the DataStage server engine processes stages sequentially in a single process on one node. Unlike the parallel engine, it does not partition data or leverage multiple processing nodes, making it suitable only for smaller workloads."
    },
    {
      id: 50,
      type: "single",
      difficulty: 2,
      question: "How can an administrator change the default APT configuration file for a DataStage project?",
      options: ["By modifying the $APT_CONFIG_FILE environment variable in the project settings via the Administrator Client", "By editing the Director Client preferences and setting a new config path", "By recompiling all jobs in the Designer Client with a new configuration reference", "By directly modifying the repository database tables using SQL commands"],
      correct: [0],
      concept: "The default APT configuration file is set through the $APT_CONFIG_FILE environment variable at the project level, managed via the Administrator Client or the DSParams file. Changing this variable redirects all jobs in the project to use the new configuration."
    },
    {
      id: 51,
      type: "single",
      difficulty: 2,
      question: "What is the Information Server architecture\'s Client Tier responsible for?",
      options: ["Hosting the desktop applications that developers and operators use to interact with DataStage", "Executing ETL jobs and managing data partitioning across processing nodes", "Storing the metadata repository and managing database connections", "Running web services and handling REST API requests from external systems"],
      correct: [0],
      concept: "The Client Tier consists of the desktop (thick client) applications installed on user workstations, including the Designer, Director, and Administrator clients. These applications provide the user interfaces for development, operations, and administration."
    },
    {
      id: 52,
      type: "single",
      difficulty: 2,
      question: "What mechanism does the Director Client use to schedule recurring job executions?",
      options: ["A built-in job scheduler that allows defining frequency, time, and date parameters", "An integration with the operating system\'s cron service exclusively", "Manual triggers requiring an operator to start each run individually", "A REST API endpoint that must be called by an external scheduler only"],
      correct: [0],
      concept: "The Director Client includes a built-in scheduler that allows operators to define recurring job schedules with parameters such as frequency (daily, weekly), start time, end date, and other timing options. External schedulers can also be used for more complex workflows."
    },
    {
      id: 53,
      type: "single",
      difficulty: 2,
      question: "In the DataStage repository, what is a shared container?",
      options: ["A reusable set of stages and links that can be embedded in multiple job designs", "A database schema shared between the repository and the target data warehouse", "A common disk volume shared by all processing nodes in the parallel engine", "A security group that grants shared access permissions to multiple users"],
      correct: [0],
      concept: "A shared container is a reusable component stored in the repository that encapsulates a set of stages and links. Once defined, it can be referenced by multiple jobs, promoting design reuse and consistency across the project."
    },
    {
      id: 54,
      type: "single",
      difficulty: 2,
      question: "What is the purpose of the DataStage command-line tools such as dsjob?",
      options: ["To programmatically run, control, and query DataStage jobs from scripts and external schedulers", "To design and compile jobs without using the Designer Client graphical interface", "To configure the APT file and processing nodes from the command line", "To directly query and modify the repository database using SQL-like syntax"],
      correct: [0],
      concept: "The dsjob command-line utility allows scripting of job operations including starting, stopping, querying status, and retrieving logs. This enables integration with external schedulers (e.g., Control-M, Autosys) and automation of operational tasks."
    },
    {
      id: 55,
      type: "single",
      difficulty: 2,
      question: "How does the DataStage Designer palette organize available stages?",
      options: ["Into categorized tabs such as Database, File, Processing, Real-Time, and Debug", "In a single alphabetical list without any categorization", "By the date they were last used in the current project", "By the license level required to access each stage type"],
      correct: [0],
      concept: "The Designer palette organizes stages into categorized tabs for easy access. Common categories include Database (for connectors), File (for file-based I/O), Processing (for transformations, joins, sorts), Real-Time (for messaging), and Debug (for testing)."
    },
    {
      id: 56,
      type: "single",
      difficulty: 2,
      question: "What happens to the job log entries when a job is run multiple times in the Director Client?",
      options: ["Each run creates a new log entry associated with a unique invocation ID, preserving history", "Each new run overwrites the previous log, keeping only the latest execution details", "Log entries accumulate in a single merged log file without distinguishing between runs", "Logs are only retained for failed runs; successful runs do not generate logs"],
      correct: [0],
      concept: "Each job execution in the Director generates a new set of log entries associated with a unique invocation ID. This preserves the complete history of all runs, allowing operators to review and compare logs from different executions."
    },
    {
      id: 57,
      type: "single",
      difficulty: 2,
      question: "What is the primary advantage of the parallel engine over the server engine in DataStage?",
      options: ["The parallel engine can scale out processing across multiple nodes and partitions for high throughput", "The parallel engine uses simpler job designs that require fewer stages", "The parallel engine eliminates the need for a repository to store job metadata", "The parallel engine can connect to databases that the server engine cannot access"],
      correct: [0],
      concept: "The parallel engine\'s key advantage is scalability. It can distribute data across multiple processing partitions and nodes, enabling pipeline and partition parallelism. This makes it suitable for enterprise-scale data volumes that the sequential server engine cannot handle efficiently."
    },
    {
      id: 58,
      type: "single",
      difficulty: 2,
      question: "In the DataStage Administrator Client, what does the \"cleanup resources\" function do?",
      options: ["It removes stale runtime artifacts such as orphaned locks, old temporary files, and dead processes", "It permanently deletes all jobs from the project that have not been compiled", "It archives the repository database to a backup location and truncates the logs", "It recalculates the node pool assignments in the APT configuration file"],
      correct: [0],
      concept: "The cleanup resources function in the Administrator Client removes stale runtime artifacts that accumulate over time, such as orphaned process locks, leftover temporary files from aborted jobs, and dead engine processes. Regular cleanup helps maintain system health."
    },
    {
      id: 59,
      type: "single",
      difficulty: 2,
      question: "What is the Information Server Web Console used for in relation to DataStage?",
      options: ["Centralized administration including user management, logging, reports, and system configuration", "Developing and compiling parallel jobs using a browser-based canvas", "Executing and monitoring job runs in real-time with streaming log output", "Designing table definitions and data connections through drag-and-drop"],
      correct: [0],
      concept: "The Information Server Web Console provides browser-based centralized administration. For DataStage, it supports user and role management, project configuration, activity logging, report generation, and system health monitoring without requiring thick client installation."
    },
    {
      id: 60,
      type: "single",
      difficulty: 2,
      question: "Which environment variable controls the default degree of parallelism in a DataStage parallel job?",
      options: ["$APT_DISABLE_COMBINATION", "$APT_NUM_PROCS", "$APT_CONFIG_FILE", "$APT_ORCHHOME"],
      correct: [1],
      concept: "The $APT_NUM_PROCS environment variable is not typically set directly; instead, the degree of parallelism is determined by the number of nodes defined in the APT configuration file. However, this variable can override the default node count to control how many processing instances are used."
    },
    {
      id: 61,
      type: "multi",
      difficulty: 2,
      question: "Which of the following are valid views available in the DataStage Director Client? (Select all that apply)",
      options: ["Job Status view", "Job Log view", "Job Schedule view", "Job Compilation view"],
      correct: [0, 1, 2],
      concept: "The Director Client provides three main views: Status (showing current job states), Log (showing detailed runtime messages), and Schedule (showing planned executions). There is no \'Job Compilation view\' in the Director; compilation is done in the Designer."
    },
    {
      id: 62,
      type: "multi",
      difficulty: 2,
      question: "Which of the following object types can be stored in the DataStage repository? (Select all that apply)",
      options: ["Job designs and job sequences", "Table definitions and column metadata", "Shared containers and local containers", "Operating system user passwords"],
      correct: [0, 1, 2],
      concept: "The repository stores DataStage metadata objects including job designs, job sequences, table definitions with column metadata, and shared containers. Operating system passwords are managed by the OS or LDAP, not the DataStage repository."
    },
    {
      id: 63,
      type: "multi",
      difficulty: 2,
      question: "Which of the following are components of the IBM Information Server architecture? (Select all that apply)",
      options: ["Client Tier", "Services Tier (middle tier)", "Engine Tier", "Presentation Tier"],
      correct: [0, 1, 2],
      concept: "IBM Information Server has a three-tier architecture: Client Tier (desktop applications), Services Tier (web services, metadata repository, security), and Engine Tier (DataStage processing engines). There is no separate \'Presentation Tier\' in the standard architecture."
    },
    {
      id: 64,
      type: "multi",
      difficulty: 2,
      question: "Which of the following are valid DataStage job types? (Select all that apply)",
      options: ["Parallel job", "Server (sequential) job", "Job sequence", "Streaming job"],
      correct: [0, 1, 2],
      concept: "DataStage supports parallel jobs (using the parallel engine), server/sequential jobs (using the server engine), and job sequences (which orchestrate multiple jobs). While streaming capabilities exist in some versions, the standard \'streaming job\' is not a traditional job type."
    },
    {
      id: 65,
      type: "multi",
      difficulty: 2,
      question: "Which actions can be performed from the DataStage Administrator Client? (Select all that apply)",
      options: ["Creating and deleting projects", "Managing user roles and permissions", "Setting project-level environment variables", "Designing data transformation logic"],
      correct: [0, 1, 2],
      concept: "The Administrator Client handles project management (create/delete), user administration (roles/permissions), and configuration (environment variables). Designing transformation logic is the responsibility of the Designer Client, not the Administrator."
    },
    {
      id: 66,
      type: "multi",
      difficulty: 2,
      question: "Which of the following are defined in a DataStage APT configuration file? (Select all that apply)",
      options: ["Processing node definitions", "Node pool groupings", "Resource disk locations", "Job scheduling parameters"],
      correct: [0, 1, 2],
      concept: "The APT configuration file defines processing nodes, node pools (logical groupings of nodes), and resource/scratch disk locations. Job scheduling is managed through the Director Client, not the APT configuration file."
    },
    {
      id: 67,
      type: "multi",
      difficulty: 2,
      question: "Which of the following can be included in a .dsx export file? (Select all that apply)",
      options: ["Job designs with stage definitions and links", "Table definitions referenced by the job", "Shared containers used within the job", "Actual data rows processed by the job"],
      correct: [0, 1, 2],
      concept: "A .dsx export includes the job design, referenced table definitions, and shared containers. It contains only metadata and design information, never actual data rows. This makes .dsx files portable and secure for migration between environments."
    },
    {
      id: 68,
      type: "multi",
      difficulty: 2,
      question: "Which of the following describe pipeline parallelism in DataStage? (Select all that apply)",
      options: ["Multiple stages execute concurrently within the same job", "Data flows between stages in a streaming fashion without full materialization", "Each stage must complete fully before the next stage begins", "It reduces overall job elapsed time by overlapping stage processing"],
      correct: [0, 1, 3],
      concept: "Pipeline parallelism allows multiple stages to execute concurrently, with data streaming between them. This overlapping execution reduces total elapsed time. The statement that each stage must complete fully before the next begins describes sequential, not pipeline, processing."
    },
    {
      id: 69,
      type: "multi",
      difficulty: 2,
      question: "Which of the following are responsibilities of the DataStage Engine Tier? (Select all that apply)",
      options: ["Executing parallel and server job logic", "Managing processing nodes and resource allocation", "Hosting the metadata repository database", "Running data partitioning and repartitioning operations"],
      correct: [0, 1, 3],
      concept: "The Engine Tier executes job logic, manages processing resources, and handles data partitioning. The metadata repository database is hosted on the Services Tier, not the Engine Tier."
    },
    {
      id: 70,
      type: "multi",
      difficulty: 2,
      question: "Which of the following are valid job statuses displayed in the Director Client? (Select all that apply)",
      options: ["Running", "Finished", "Aborted", "Compiling"],
      correct: [0, 1, 2],
      concept: "Valid Director Client job statuses include Running (currently executing), Finished (completed successfully), and Aborted (terminated due to error or manual stop). \"Compiling\" is not a Director status; compilation happens in the Designer Client."
    },
    {
      id: 71,
      type: "multi",
      difficulty: 2,
      question: "Which environment variables are commonly configured for DataStage parallel jobs? (Select all that apply)",
      options: ["$APT_CONFIG_FILE for the APT configuration path", "$APT_ORCHHOME for the parallel engine installation directory", "$TMPDIR for temporary file storage location", "$DS_DESIGNER_PATH for the client installation"],
      correct: [0, 1, 2],
      concept: "$APT_CONFIG_FILE points to the configuration file, $APT_ORCHHOME specifies the parallel engine home directory, and $TMPDIR sets the temporary file location. $DS_DESIGNER_PATH is not a standard DataStage environment variable for parallel job configuration."
    },
    {
      id: 72,
      type: "multi",
      difficulty: 2,
      question: "Which of the following operations require the Designer Client? (Select all that apply)",
      options: ["Creating a new parallel job design", "Compiling a job for execution", "Modifying stage properties and column mappings", "Scheduling a job to run at a specific time"],
      correct: [0, 1, 2],
      concept: "The Designer Client is required for creating job designs, compiling jobs, and modifying stage configurations. Scheduling job executions is performed in the Director Client, not the Designer."
    },
    {
      id: 73,
      type: "multi",
      difficulty: 2,
      question: "What are characteristics of the SMP architecture as it applies to DataStage? (Select all that apply)",
      options: ["Multiple processors share the same memory space", "All processors access a common I/O subsystem", "Each processor has its own dedicated memory and storage", "It is commonly used for single-server DataStage installations"],
      correct: [0, 1, 3],
      concept: "SMP (Symmetric Multiprocessing) features shared memory and I/O across all processors, making it common for single-server installations. Dedicated memory per processor describes MPP (Massively Parallel Processing), not SMP."
    },
    {
      id: 74,
      type: "multi",
      difficulty: 2,
      question: "Which of the following are palette categories in the DataStage Designer Client? (Select all that apply)",
      options: ["Database stages", "File stages", "Processing stages", "Visualization stages"],
      correct: [0, 1, 2],
      concept: "The Designer palette includes categories for Database (connectors to RDBMS), File (sequential, dataset, complex flat file), and Processing (Transformer, Join, Sort, Aggregator). There is no \'Visualization stages\' category in the standard DataStage palette."
    },
    {
      id: 75,
      type: "multi",
      difficulty: 2,
      question: "Which of the following describe the DataStage repository database? (Select all that apply)",
      options: ["It stores all job metadata and design information", "It is hosted on a relational database management system", "It can be backed up and restored using standard database tools", "It stores the actual source and target data processed by ETL jobs"],
      correct: [0, 1, 2],
      concept: "The repository database stores metadata (job designs, table definitions, etc.) on an RDBMS like DB2 or Oracle, and can be backed up using standard database utilities. It does not store the actual business data processed by ETL jobs."
    },
    {
      id: 76,
      type: "multi",
      difficulty: 3,
      question: "When configuring an APT configuration file for an SMP server with 8 CPU cores, which of the following are valid considerations? (Select all that apply)",
      options: ["Defining multiple logical nodes mapped to the same physical server", "Configuring separate resource disk paths for each node pool to avoid I/O contention", "Setting the number of nodes to roughly match the number of available CPU cores", "Defining each logical node on a separate physical server for true MPP"],
      correct: [0, 1, 2],
      concept: "On an SMP server, multiple logical nodes map to the same physical machine, resource disks should be distributed to reduce I/O contention, and node count should approximate available cores. Separate physical servers would be an MPP configuration, not SMP."
    },
    {
      id: 77,
      type: "multi",
      difficulty: 3,
      question: "Which of the following are benefits of using shared containers in DataStage? (Select all that apply)",
      options: ["They promote reuse of common transformation logic across multiple jobs", "They reduce maintenance effort since changes propagate to all referencing jobs", "They improve runtime performance by caching data in shared memory", "They enforce design consistency across the development team"],
      correct: [0, 1, 3],
      concept: "Shared containers promote reusability, reduce maintenance (changes apply everywhere), and enforce consistency. They do not inherently improve runtime performance through shared memory caching; they are a design-time, not runtime, optimization."
    },
    {
      id: 78,
      type: "multi",
      difficulty: 3,
      question: "What are the implications of having an incorrectly configured APT file in DataStage? (Select all that apply)",
      options: ["Jobs may fail at runtime with resource allocation errors", "The degree of parallelism may not match available hardware, causing poor performance", "Temporary data may fill up disk space if resource disk paths are misconfigured", "The Designer Client will be unable to open or display job designs"],
      correct: [0, 1, 2],
      concept: "An incorrect APT configuration can cause runtime failures, suboptimal parallelism, and disk space issues. However, it does not affect the Designer Client\'s ability to open job designs, as the Designer operates independently of the APT runtime configuration."
    },
    {
      id: 79,
      type: "multi",
      difficulty: 3,
      question: "Which of the following are valid methods to configure environment variables in DataStage? (Select all that apply)",
      options: ["Through the Administrator Client at the project level", "By editing the DSParams file directly on the engine server", "By setting them at the individual job level in the Designer Client", "By modifying the Director Client\'s display preferences panel"],
      correct: [0, 1, 2],
      concept: "Environment variables can be set through the Administrator Client (project level), by directly editing the DSParams file, or at the individual job level in job properties. The Director Client\'s display preferences are for UI settings, not engine environment variables."
    },
    {
      id: 80,
      type: "multi",
      difficulty: 3,
      question: "In a multi-tier Information Server deployment, which of the following are valid architecture configurations? (Select all that apply)",
      options: ["All tiers installed on a single server for development", "Services tier and engine tier on separate servers for production scalability", "Multiple engine tiers connected to a single services tier for workload distribution", "Client tier installed on the engine tier server to reduce network latency"],
      correct: [0, 1, 2],
      concept: "Information Server supports flexible deployment: all tiers on one server (development), separate servers for services and engine tiers (production), and multiple engine tiers with one services tier (scale-out). While possible, installing clients on the engine server is not a standard architectural recommendation."
    },
    {
      id: 81,
      type: "multi",
      difficulty: 3,
      question: "Which of the following actions should be performed during DataStage project migration between environments? (Select all that apply)",
      options: ["Export jobs and dependent objects as .dsx files from the source environment", "Update environment variables to reflect the target environment paths and connections", "Recompile all jobs after importing them into the target project", "Copy the APT configuration file without any modifications to the target server"],
      correct: [0, 1, 2],
      concept: "Migration requires exporting .dsx files, updating environment-specific settings (paths, connections), and recompiling jobs in the target environment. The APT configuration file typically needs modification to reflect the target server\'s hardware topology."
    },
    {
      id: 82,
      type: "multi",
      difficulty: 3,
      question: "Which of the following are characteristics of MPP architecture in DataStage? (Select all that apply)",
      options: ["Each processing node has its own dedicated memory and storage", "Nodes communicate through a high-speed network interconnect", "All nodes share a single memory address space for data exchange", "It enables horizontal scaling by adding more independent nodes"],
      correct: [0, 1, 3],
      concept: "MPP architecture features dedicated memory per node, inter-node communication via network, and horizontal scalability. Shared memory address space is a characteristic of SMP, not MPP."
    },
    {
      id: 83,
      type: "multi",
      difficulty: 3,
      question: "Which of the following are valid reasons to create separate DataStage projects within the same installation? (Select all that apply)",
      options: ["To isolate development, testing, and production job designs", "To separate jobs by business domain or functional area", "To apply different security policies and user access controls per project", "To use different parallel engine versions for each project simultaneously"],
      correct: [0, 1, 2],
      concept: "Separate projects enable lifecycle isolation (dev/test/prod), business domain separation, and independent security policies. However, all projects within an installation share the same parallel engine version; you cannot run different engine versions per project."
    },
    {
      id: 84,
      type: "multi",
      difficulty: 3,
      question: "Which of the following are stored in the DSParams file? (Select all that apply)",
      options: ["Project-level environment variable settings", "Default job parameter values for the project", "Engine tier tuning parameters like buffer sizes", "The compiled OSH scripts for all parallel jobs"],
      correct: [0, 1, 2],
      concept: "The DSParams file stores project-level configuration including environment variables, default parameter values, and tuning settings. Compiled OSH scripts are stored separately in the job runtime directory, not in DSParams."
    },
    {
      id: 85,
      type: "multi",
      difficulty: 3,
      question: "When troubleshooting a failed parallel job, which of the following information sources should be consulted? (Select all that apply)",
      options: ["The Director Client log view for runtime error messages and stage-level details", "The engine tier system log files for low-level engine errors", "The OSH script generated during compilation for execution plan review", "The Designer palette configuration for stage version compatibility"],
      correct: [0, 1, 2],
      concept: "Troubleshooting involves checking the Director log (runtime errors), engine system logs (low-level issues), and the generated OSH script (execution plan). The palette configuration is a design-time UI element and does not contain troubleshooting information."
    },
    {
      id: 86,
      type: "tf",
      difficulty: 3,
      question: "The DataStage Designer Client can be used to execute jobs directly without using the Director Client.",
      options: ["True - the Designer Client has a built-in run button that compiles and executes jobs directly", "False - jobs can only be executed through the Director Client or command-line tools"],
      correct: [0],
      concept: "The Designer Client does have the ability to run jobs directly using the run button or toolbar option. While the Director is the primary operational tool for job execution, developers commonly run and test jobs from within the Designer during development."
    },
    {
      id: 87,
      type: "tf",
      difficulty: 3,
      question: "The DataStage repository database can only be hosted on IBM DB2 and no other RDBMS is supported.",
      options: ["True - IBM DB2 is the only supported repository database for Information Server", "False - the repository can also be hosted on Oracle, Microsoft SQL Server, and other supported RDBMS"],
      correct: [1],
      concept: "While IBM DB2 is the most common and recommended repository database, Information Server also supports Oracle and other RDBMS platforms for hosting the repository. The specific supported databases depend on the Information Server version."
    },
    {
      id: 88,
      type: "tf",
      difficulty: 3,
      question: "In an SMP configuration, multiple logical processing nodes defined in the APT file can map to a single physical server.",
      options: ["True - SMP allows multiple logical nodes on the same physical machine sharing memory and I/O", "False - each logical node in the APT file must correspond to a separate physical server"],
      correct: [0],
      concept: "In SMP configurations, multiple logical processing nodes are defined on a single physical server. They share the server\'s memory and I/O resources. This is different from MPP where each node typically resides on a separate physical machine."
    },
    {
      id: 89,
      type: "tf",
      difficulty: 3,
      question: "The .dsx export file format is a binary format that cannot be read or edited with a text editor.",
      options: ["True - .dsx files are compiled binary archives that require the Designer Client to interpret", "False - .dsx files are XML-based text files that can be viewed and edited with any text editor"],
      correct: [1],
      concept: "The .dsx file format is XML-based and human-readable. While it is not recommended to manually edit .dsx files (as errors can corrupt the import), they can be opened and inspected with any text editor for review or troubleshooting."
    },
    {
      id: 90,
      type: "tf",
      difficulty: 3,
      question: "The Director Client\'s schedule view can only display schedules; it cannot be used to create new job schedules.",
      options: ["True - the schedule view is read-only and requires the Administrator Client to create schedules", "False - the schedule view in the Director allows both viewing and creating new job schedules"],
      correct: [1],
      concept: "The Director Client\'s schedule view is fully functional for both viewing existing schedules and creating new ones. Operators can define new schedules with frequency, timing, and other parameters directly from the Director Client."
    },
    {
      id: 91,
      type: "tf",
      difficulty: 3,
      question: "A DataStage parallel job must be recompiled every time the APT configuration file is changed.",
      options: ["True - the compiled job embeds the APT configuration and requires recompilation for changes to take effect", "False - the APT configuration is read at runtime, so jobs do not need recompilation when it changes"],
      correct: [1],
      concept: "The APT configuration file is read at runtime by the parallel engine when a job starts executing. Changes to the APT file take effect on the next job run without requiring recompilation, since the compiled OSH script references the configuration dynamically."
    },
    {
      id: 92,
      type: "tf",
      difficulty: 3,
      question: "Environment variables set at the job level in DataStage override the same variables set at the project level.",
      options: ["True - job-level settings take precedence over project-level settings for the same variable", "False - project-level settings always take precedence regardless of job-level overrides"],
      correct: [0],
      concept: "DataStage follows a hierarchical precedence for environment variables: job-level settings override project-level settings, which in turn override system-level defaults. This allows fine-grained control where specific jobs can have customized configurations."
    },
    {
      id: 93,
      type: "tf",
      difficulty: 3,
      question: "The DataStage repository stores the actual data (rows and columns) processed by ETL jobs alongside the job metadata.",
      options: ["True - the repository contains both job metadata and processed data for auditing purposes", "False - the repository stores only metadata such as job designs and table definitions, not actual processed data"],
      correct: [1],
      concept: "The DataStage repository is exclusively a metadata store. It contains job designs, table definitions, shared containers, and configuration information. The actual data processed by ETL jobs flows through the engine tier and is stored in source/target systems, not in the repository."
    },
    {
      id: 94,
      type: "tf",
      difficulty: 3,
      question: "Node pools in the APT configuration file allow different stages within a job to be assigned to different groups of processing nodes.",
      options: ["True - node pools enable targeted resource allocation where specific stages can run on designated node groups", "False - all stages in a job must execute on the same node pool defined in the configuration"],
      correct: [0],
      concept: "Node pools allow administrators to group nodes by resource characteristics and assign different stages to different pools. For example, I/O-intensive stages can be assigned to nodes with fast disks, while CPU-intensive stages run on nodes with more processing power."
    },
    {
      id: 95,
      type: "tf",
      difficulty: 3,
      question: "The DataStage parallel engine can only execute parallel jobs and cannot run server (sequential) jobs.",
      options: ["True - server jobs require the separate server engine and cannot use the parallel engine", "False - the parallel engine can also execute server jobs through backward compatibility mode"],
      correct: [0],
      concept: "The parallel engine and server engine are separate processing engines. Server (sequential) jobs run exclusively on the server engine, while parallel jobs run on the parallel engine. They are not interchangeable; each job type requires its corresponding engine."
    },
    {
      id: 96,
      type: "tf",
      difficulty: 3,
      question: "The dsjob command-line utility can be used to start, stop, and query the status of DataStage jobs without the Director Client GUI.",
      options: ["True - dsjob provides full command-line control over job execution and status queries", "False - the Director Client GUI is the only way to interact with running DataStage jobs"],
      correct: [0],
      concept: "The dsjob command-line utility provides comprehensive job management capabilities including starting jobs, stopping running jobs, querying job status, and retrieving log information. It is essential for scripting, automation, and integration with external job schedulers."
    },
    {
      id: 97,
      type: "tf",
      difficulty: 3,
      question: "When multiple developers work on the same DataStage project simultaneously, the repository automatically handles object locking to prevent conflicts.",
      options: ["True - the repository implements object-level locking when a developer opens a job for editing", "False - DataStage does not provide any concurrency control and developers must coordinate manually"],
      correct: [0],
      concept: "The DataStage repository implements object-level locking. When a developer opens a job for editing, the repository locks that object to prevent other developers from making conflicting changes simultaneously. This ensures design integrity in multi-developer environments."
    },
    {
      id: 98,
      type: "tf",
      difficulty: 3,
      question: "Changing the $APT_CONFIG_FILE environment variable at the project level affects all jobs in that project unless overridden at the job level.",
      options: ["True - project-level $APT_CONFIG_FILE applies to all jobs unless individual jobs specify a different value", "False - each job must explicitly reference the APT configuration file regardless of project settings"],
      correct: [0],
      concept: "The $APT_CONFIG_FILE set at the project level serves as the default for all parallel jobs in that project. Individual jobs can override this by setting the variable at the job level, providing flexibility to use different configurations for different workloads."
    },
    {
      id: 99,
      type: "tf",
      difficulty: 3,
      question: "The Information Server Services Tier must always be installed on a separate physical server from the Engine Tier in production deployments.",
      options: ["True - production deployments require physical separation of the services and engine tiers", "False - while separate servers are recommended for production, both tiers can coexist on the same server"],
      correct: [1],
      concept: "While separating the Services Tier and Engine Tier onto different servers is a best practice for production (for performance and scalability), it is not a strict requirement. Both tiers can be installed on the same server, which is common in development and small-scale environments."
    },
    {
      id: 100,
      type: "tf",
      difficulty: 3,
      question: "A DataStage job sequence is itself a type of job that can be monitored and scheduled in the Director Client just like parallel and server jobs.",
      options: ["True - job sequences appear in the Director Client and can be scheduled, run, and monitored like other jobs", "False - job sequences are design-time constructs only and cannot be executed or monitored independently"],
      correct: [0],
      concept: "Job sequences are a distinct job type in DataStage that orchestrate the execution of multiple jobs with dependencies and conditional logic. They are treated as first-class jobs in the Director Client and can be scheduled, executed, monitored, and have their logs reviewed just like parallel and server jobs."
    }
  ]
};
